name: kalaapp
description: "onlab 2 msc"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  file_picker: ^9.0.2
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true




